# Generated by Django 3.1.2 on 2020-10-22 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('faculty', models.CharField(choices=[('FST', 'FST'), ('FBS', 'FBS'), ('FASS', 'FASS'), ('FSSS', 'FSSS')], max_length=200)),
                ('department', models.CharField(choices=[('General', 'General'), ('AIS', 'AIS'), ('Marketing', 'Marketing'), ('Finance & Banking', 'Finance & Banking'), ('Management', 'Management'), ('ICT', 'ICT'), ('ES', 'ES'), ('English', 'English'), ('Economics', 'Economics'), ('Sociology', 'Sociology'), ('DS', 'DS'), ('PA', 'PA'), ('DHSM', 'DHSM'), ('Law', 'Law'), ('IR', 'IR'), ('MCJ', 'MCJ'), ('PHRDS', 'PHRDS')], max_length=200)),
                ('roll', models.IntegerField()),
                ('batch', models.IntegerField()),
                ('passing_year', models.IntegerField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='files/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
