# Generated by Django 3.1.2 on 2020-10-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Number Theory', 'Number Theory'), ('Dynamic Programming', 'Dynamic Programming'), ('Data Structure', 'Data Structure'), ('Graph', 'Graph'), ('String', 'String'), ('Greedy', 'Greedy'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=250),
        ),
    ]
